Dev 0.8.0
NicoAiko/mikazuki pull request #208
Opened 2020-09-30 12:57 UTC by NicoAiko

Fixes #74 #80 #157 #169 #202 

#157 is currently circumvented by having the progress bar removed until another updates comes that fixes the whole update behaviour at once.

# New stuff
- The list overview has been overhauled with less space taken by empty containers
- Set the score directly on the overview by clicking on the score chip.
- The Settings dialog has been completely remade with more settings to set, flags for language settings, and styling settings
  - Set your own navigation bar background by adding an AniList Banner!
  - Set the preferred language of the media titles and your preferred scoring system directly in the settings
- The Season preview has been completely overhauled with bigger images, more information and fixed navigation between seasons. Also the default season is the next to come now.
- The airing media now has a little yellow-ish progress bar that indicates the progress of the media itself (how many episodes have already aired)

# Bug Fixes

- #157 is currently circumvented by having the progress bar removed until another updates comes that fixes the whole update behaviour at once.
- #169 now adds the title to the planning list
- #202 The days watched progress bar middle value on the home view now shows the correct values

# Other changes
- The Changelog is now written as Markdown file
- A lot of dependencies have been updated

2020-09-30 13:47 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +          "title": "Change score"
Changez le score

2020-09-30 13:47 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +        "season": "Season",
Saison

2020-09-30 13:48 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +        "title": "Season Preview Parameters",
Paramètres de prévisualisation de la saison

2020-09-30 13:48 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +        "yearOfSeason": "Year of Season"
Année de la saison

2020-09-30 13:48 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +          "headline": "AniList User Account Settings",
Paramètres du compte AniList

2020-09-30 13:49 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +          "scoringFormat": "Scoring Format",
Format du score

2020-09-30 13:50 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +          "scoringFormatHint": "This setting defines how you can score your list entries.",
Ce paramètre définie comment vous pouvez noter vos entrés de liste

2020-09-30 13:51 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +          "showExplicitContent": "Show explicit content (18+ Content)",
Montrer du contenu explicite (18+)

2020-09-30 13:51 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +          "showExplicitContentHint": "This setting defines if 18+ content will be shown.",
Ce paramètre défini si le contenu 18+ est afficher

2020-09-30 13:52 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +          "subHeadline": "Changing these settings may take some time until they come into effect!",
Changer ces paramètres peuvent prendre du temps jusqu'à ce qu'ils deviennent actif

2020-09-30 13:53 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +          "userTitleLanguage": "Title Language",
Langue du titre

2020-09-30 13:53 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +          "userTitleLanguageHint": "This setting defines which title is used for displaying the media's name."
Ce paramètre défini quel titre va être utilisé pour afficher le nom du média

2020-09-30 13:54 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +        "navigationActiveItemColour": "Active Navigation item colour",
Couleur active pour la navigation

2020-09-30 13:54 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +        "navigationBackgroundBrightness": "Navigation Background Brightness",
Luminosité de l'arrière plan pour la navigation

2020-09-30 13:55 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +        "navigationBackgroundBlurriness": "Navigation Background Blurriness",
Flou d'arrière plan pour la navigation

2020-09-30 13:55 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +        "initialListItemAmount": "Initial amount of shown list items",
Montant initial d'objets affichés

2020-09-30 13:57 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +          "subtitle": "The selected amount functions as a limit. If more items are shown at the same time, all animations are deactivated to preserve performance."
Le montant sélectionné de fonctions a une limite. Si plus d'objets sont affichés au même moment, toutes les animations sont désactivées pour préserver les performances

2020-09-30 14:00 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +          "POINT_10_DECIMAL": "10 Points Decimal (5.5 / 10)",
10 Points avec décimales

2020-09-30 14:01 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +          "POINT_3": "3 Point Smileys",
3 Point émojis

2020-09-30 14:04 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +          "ENGLISH": "English (How to keep a mummy)",
Anglais (How to keep a mummy)

2020-09-30 14:04 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +          "ENGLISH_STYLISED": "Stylised English",
Anglais stylisé

2020-09-30 14:05 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +          "NATIVE_STYLISED": "Stylised Native",
Natif stylisé

2020-09-30 14:06 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +          "NATIVE": "Native (ミイラの飼い方)",
Original

2020-09-30 14:06 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +          "ROMAJI_STYLISED": "Stylised Romaji"
Romaji stylisé

2020-09-30 14:07 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +        "cancelled": "CANCELLED",
ANNULÉ

2020-09-30 14:08 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +        "finished": "FINISHED",
TERMINÉ

2020-09-30 14:08 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +        "not_yet_released": "NOT YET RELEASED",
PAS ENCORE SORTI

2020-09-30 14:13 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +        "releasing": "RELEASING"
EN TRAIN DE SORTIR

2020-09-30 14:13 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +      "automatic": "Automatic",
Automatique

2020-09-30 14:13 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +      "black": "Black",
Noir

2020-09-30 14:13 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +      "white": "White"
Blanc

2020-09-30 14:14 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +      "all": "All",
Tout

2020-09-30 14:14 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +      "disabled": "Disabled"
Désactivé

2020-09-30 14:14 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +        "episodes": "By Episodes",
Par épisodes

2020-09-30 14:14 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +        "score": "By Score",
Par scores

2020-09-30 14:14 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +        "title": "By Title"
Par titres

2020-09-30 14:14 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +        "asc": "Ascending",
Ascendant

2020-09-30 14:15 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +        "desc": "Descending"
Descendant

2020-09-30 14:15 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +      "by": {
Par

2020-09-30 14:15 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +    "sorting": {
Trier

2020-09-30 14:15 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +    "status": {
Statut

2020-09-30 14:16 UTC, ExtazUxy commented on src/assets/locales/fr.json
> +    "colours": {
Couleurs

2020-09-30 14:19 UTC, NicoAiko commented on src/assets/locales/fr.json
> +        "nextAiringEpisode": "L'épisode {0} sera diffusé le {1}",
```suggestion
        "nextAiringEpisode": "L'épisode {0} sera diffusé {1}",
```

2020-09-30 14:26 UTC, NicoAiko commented on src/assets/locales/fr.json
> +          "headline": "List animation activity",
```suggestion
          "headline": "Limite de la liste d'animation",
```

2020-09-30 14:43 UTC, nattadasu requested changes
Add translation for Malay and Indonesian. For Arabic, I'll add some of words that's (I'm hoping) ok.

2020-09-30 14:43 UTC, nattadasu commented on src/assets/locales/id.json
> +    "filter": "Filter"
```suggestion
    "filter": "Saring"
```

2020-09-30 14:43 UTC, nattadasu commented on src/assets/locales/id.json
> +        "yearOfSeason": "Year of Season"
```suggestion
        "yearOfSeason": "Tahun Musim"
```

2020-09-30 14:43 UTC, nattadasu commented on src/assets/locales/id.json
> +        "releasing": "RELEASING"
```suggestion
        "cancelled": "DIBATALKAN",
        "finished": "SELESAI",
        "not_yet_released": "BELUM DIRILIS",
        "releasing": "RILIS"
```

2020-09-30 14:43 UTC, nattadasu commented on src/assets/locales/id.json
> +        "title": "By Title"
```suggestion
        "episodes": "Berdasarkan Episode",
        "score": "Berdasarkan Skor",
        "title": "Berdasarkan Judul"
```

2020-09-30 14:43 UTC, nattadasu commented on src/assets/locales/id.json
> +        "desc": "Descending"
```suggestion
        "asc": "Menaik",
        "desc": "Menurun"
```

2020-09-30 14:43 UTC, nattadasu commented on src/assets/locales/my.json
> +    "filter": "Filter"
```suggestion
    "filter": "Tapis"
```

2020-09-30 14:43 UTC, nattadasu commented on src/assets/locales/my.json
> +        "yearOfSeason": "Year of Season"
```suggestion
        "season": "Musim",
        "title": "Parameter Pratonton Musim",
        "yearOfSeason": "Tahun Musim"
```

2020-09-30 14:43 UTC, nattadasu commented on src/assets/locales/my.json
> +          "POINT_5": "5 Points (3 / 5)"
```suggestion
          "POINT_10": "10 Mata (5 / 10)",
          "POINT_100": "100 Mata (55 / 100)",
          "POINT_10_DECIMAL": "10 Mata Perpuluhan (5.5 / 10)",
          "POINT_3": "3 Mata Smileys",
          "POINT_5": "5 Mata (3 / 5)"
```

2020-09-30 14:43 UTC, nattadasu commented on src/assets/locales/my.json
> +          "ROMAJI_STYLISED": "Stylised Romaji"
```suggestion
          "ENGLISH": "Inggeris (How to keep a mummy)",
          "ENGLISH_STYLISED": "Bergaya Inggeris",
          "NATIVE": "Asli (ミイラの飼い方)",
          "NATIVE_STYLISED": "Bergaya Asli",
          "ROMAJI": "Romaji (Miira no Kaikata)",
          "ROMAJI_STYLISED": "Bergaya Romaji"
```

2020-09-30 14:43 UTC, nattadasu commented on src/assets/locales/my.json
> +        "title": "By Title"
```suggestion
        "episodes": "Mengikut Episod",
        "score": "Mengikut Poin",
        "title": "Mengikut Tajuk"
```

2020-09-30 14:43 UTC, nattadasu commented on src/assets/locales/my.json
> +        "desc": "Descending"
```suggestion
        "asc": "Menaik",
        "desc": "Menurun"
```

2020-09-30 14:43 UTC, nattadasu commented on src/assets/locales/ar.json
> +        "translators": "Translators"
```suggestion
        "translators": "مترجمين"
```

2020-09-30 14:43 UTC, nattadasu commented on src/assets/locales/ar.json
> +      "white": "White"
```suggestion
      "automatic": "تلقائي",
      "black": "أسود",
      "white": "أبيض"
```

2020-09-30 14:43 UTC, nattadasu commented on src/assets/locales/ar.json
> +    "filter": "Filter"
```suggestion
    "filter": "أسود"
```

2020-09-30 14:43 UTC, nattadasu commented on src/assets/locales/ar.json
> +        "yearOfSeason": "Year of Season"
```suggestion
        "season": "الموسم",
        "title": "معلمات معاينة الموسم",
        "yearOfSeason": "عام الموسم"
```

2020-09-30 16:52 UTC, CeStain submitted a review, later dismissed

2020-09-30 16:52 UTC, CeStain commented on src/assets/locales/ar.json
>      "added": "يضاف إلى القائمة",
```suggestion
     "added": "تمت الإضافة",
```

2020-09-30 16:52 UTC, CeStain commented on src/assets/locales/ar.json
>      "addToPlanToWatch": "إضافة إلى قائمة التخطيط",
```suggestion
     "addToPlanToWatch": "إضافة إلى المخطط لمشاهدته",
```

2020-09-30 16:52 UTC, CeStain commented on src/assets/locales/ar.json
>      "back": "رجع",
```suggestion
     "back": "رجوع",
```

2020-09-30 16:52 UTC, CeStain commented on src/assets/locales/ar.json
>      "loading": "جار التحميل...",
```suggestion
     "loading": "جاري التحميل...",
```

2020-09-30 16:52 UTC, CeStain commented on src/assets/locales/ar.json
>          "airingFinished": " بث الانتهاء",
```suggestion
         "airingFinished": " انتهى البث",
```

2020-09-30 16:52 UTC, CeStain commented on src/assets/locales/ar.json
>          "missingEpisodes": "حلقة واحدة لمشاهدة | {count} حلقات لمشاهدة",
```suggestion
         "missingEpisodes": "حلقة واحدة للمشاهدة | {count} حلقات للمشاهدة",
```

2020-09-30 16:52 UTC, CeStain commented on src/assets/locales/ar.json
>      "adultContent": "تعتبر هذه الوسائط محتوى للبالغين! المشاهد حرية التقدير.",
```suggestion
     "adultContent": "تعتبر هذه الوسائط محتوى للبالغين! يُنصح بتقدير المشاهد.",
```

2020-09-30 16:52 UTC, CeStain commented on src/assets/locales/ar.json
>          "airedOn": "تم البث على {0}",
```suggestion
         "airedOn": "تم البث في {0}",
```

2020-09-30 16:52 UTC, CeStain commented on src/assets/locales/ar.json
> +      "startDate": "بداء البث:",
```suggestion
      "startDate": "بدء البث:",
```

2020-09-30 16:52 UTC, CeStain commented on src/assets/locales/ar.json
> +        "supporters": "الأنصار",
```suggestion
        "supporters": "الداعمين",
```

2020-09-30 16:52 UTC, CeStain commented on src/assets/locales/ar.json
>          "changesIn": "أحدث التغييرات بـ {0}"
```suggestion
         "changesIn": "أحدث التغييرات في {0}"
```

2020-09-30 16:52 UTC, CeStain commented on src/assets/locales/ar.json
>          "fall": "الخريف",
```suggestion
         "fall": "خريف",
```

2020-09-30 16:52 UTC, CeStain commented on src/assets/locales/ar.json
>          "autumn": "الخريف",
```suggestion
         "autumn": "خريف",
```

2020-09-30 16:52 UTC, CeStain commented on src/assets/locales/ar.json
>          "winter": "الشتاء"
```suggestion
         "winter": "الشتاء"
```
شتاء

2020-09-30 17:42 UTC, NicoAiko commented on src/assets/locales/ar.json
>      "added": "يضاف إلى القائمة",
Please remove the one leading space
![image](https://user-images.githubusercontent.com/22343587/94720627-02dbe100-0355-11eb-9bfe-fd202a874494.png)

2020-09-30 17:42 UTC, NicoAiko commented on src/assets/locales/ar.json
>      "addToPlanToWatch": "إضافة إلى قائمة التخطيط",
Please also remove the leading space here

2020-09-30 17:42 UTC, NicoAiko commented on src/assets/locales/ar.json
>      "back": "رجع",
Leading space

2020-09-30 17:42 UTC, NicoAiko commented on src/assets/locales/ar.json
>      "loading": "جار التحميل...",
Leading space

2020-09-30 17:42 UTC, NicoAiko commented on src/assets/locales/ar.json
>          "airingFinished": " بث الانتهاء",
leading Space

2020-09-30 17:43 UTC, NicoAiko commented on src/assets/locales/ar.json
>          "winter": "الشتاء"
Your suggestion is not in the code and it has a leading space

2020-09-30 19:06 UTC, CeStain commented on src/assets/locales/ar.json
> +    "filter": "Filter"
Filter should be "فرز" here.

2020-09-30 20:05 UTC, NicoAiko commented
- [ ] German
- [ ] English
- [ ] French
- [ ] Italian
- [ ] Spanish
- [ ] Portuguese
- [ ] Japanese
- [ ] Malay
- [ ] Indonesian
- [ ] Chinese
- [ ] Arabic

2020-10-01 13:00 UTC, NicoAiko commented
@Knocks83 Can you do the Italian translation please?

2020-10-01 18:26 UTC, Knocks83 requested changes

2020-10-01 18:26 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "headline": "List animation activity",
"headline": "Limite oggetti per le animazioni",

2020-10-01 18:26 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "subtitle": "The selected amount functions as a limit. If more items are shown at the same time, all animations are deactivated to preserve performance."
"subtitle": "Il valore scelto funziona come limite: se l'utente visualizza più di quel numero di oggetti allo stesso tempo tutte le animazioni vengono disattivate per preservare le prestazioni."

2020-10-01 18:40 UTC, NicoAiko commented on src/assets/locales/it.json
> +          "title": "Change score"
```suggestion
          "title": "Cambia valutazione"
```

2020-10-01 18:41 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "title": "Change score"
```suggestion
          "title": "Cambia valutazione"
```

2020-10-01 18:41 UTC, NicoAiko commented on src/assets/locales/it.json
> +        "season": "Season",
```suggestion
        "season": "Stagione",
```

2020-10-01 18:42 UTC, Knocks83 commented on src/assets/locales/it.json
> +        "season": "Season",
```suggestion
        "season": "Stagione",
```

2020-10-01 18:42 UTC, Knocks83 commented on src/assets/locales/it.json
> +        "title": "Season Preview Parameters",
```suggestion
        "title": "Parametri Anteprima Stagione",
```

2020-10-01 18:42 UTC, Knocks83 commented on src/assets/locales/it.json
> +        "yearOfSeason": "Year of Season"
```suggestion
        "yearOfSeason": "Anno della Stagione"
```

2020-10-01 18:43 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "headline": "AniList User Account Settings",
```suggestion
          "headline": "Impostazioni Account AniList",
```

2020-10-01 18:43 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "scoringFormat": "Scoring Format",
```suggestion
          "scoringFormat": "Formato Valutazioni",
```

2020-10-01 18:43 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "scoringFormatHint": "This setting defines how you can score your list entries.",
```suggestion
          "scoringFormatHint": "Questa impostazione definisce come puoi valutare le voci della tua lista.",
```

2020-10-01 18:43 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "showExplicitContent": "Show explicit content (18+ Content)",
```suggestion
          "showExplicitContent": "Mostra contenuti espliciti (18+)",
```

2020-10-01 18:44 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "showExplicitContentHint": "This setting defines if 18+ content will be shown.",
```suggestion
          "showExplicitContentHint": "Questa impostazione definisce se verranno visualizzati i contenuti 18+",
```

2020-10-01 18:44 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "subHeadline": "Changing these settings may take some time until they come into effect!",
```suggestion
          "subHeadline": "Potrebbe volerci un po' di tempo prima che i cambiamenti diventino definitivi!",
```

2020-10-01 18:44 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "userTitleLanguage": "Title Language",
```suggestion
          "userTitleLanguage": "Lingua del titolo",
```

2020-10-01 18:45 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "userTitleLanguageHint": "This setting defines which title is used for displaying the media's name."
```suggestion
          "userTitleLanguageHint": "Questa impostazione definisce quale lingua verrà utilizzata per visualizzare i titoli dei media"
```

2020-10-01 18:45 UTC, Knocks83 commented on src/assets/locales/it.json
> +        "navigationActiveItemColour": "Active Navigation item colour",
```suggestion
        "navigationActiveItemColour": "Colore dell'elemento attivo nella barra di navigazione",
```

2020-10-01 18:45 UTC, Knocks83 commented on src/assets/locales/it.json
> +        "navigationBackgroundBrightness": "Navigation Background Brightness",
```suggestion
        "navigationBackgroundBrightness": "Luminosità sfondo barra di navigazione",
```

2020-10-01 18:45 UTC, Knocks83 commented on src/assets/locales/it.json
> +        "navigationBackgroundBlurriness": "Navigation Background Blurriness",
```suggestion
        "navigationBackgroundBlurriness": "Effetto sfocato barra di navigazione",
```

2020-10-01 18:46 UTC, Knocks83 commented on src/assets/locales/it.json
> +        "initialListItemAmount": "Initial amount of shown list items",
```suggestion
        "initialListItemAmount": "Quantità iniziale di elementi mostrati nella lista",
```

2020-10-01 18:46 UTC, Knocks83 commented on src/assets/locales/it.json
> +        "translators": "Translators"
```suggestion
        "translators": "Traduttori"
```

2020-10-01 18:46 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "POINT_10": "10 Points (5 / 10)",
```suggestion
          "POINT_10": "10 Punti (5 / 10)",
```

2020-10-01 18:46 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "POINT_100": "100 Points (55 / 100)",
```suggestion
          "POINT_100": "100 Punti (55 / 100)",
```

2020-10-01 18:46 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "POINT_10_DECIMAL": "10 Points Decimal (5.5 / 10)",
```suggestion
          "POINT_10_DECIMAL": "10 Punti Decimali (5.5 / 10)",
```

2020-10-01 18:46 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "POINT_3": "3 Point Smileys",
```suggestion
          "POINT_3": "3 Punti Emoji",
```

2020-10-01 18:47 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "POINT_5": "5 Points (3 / 5)"
```suggestion
          "POINT_5": "5 Punti (3 / 5)"
```

2020-10-01 18:47 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "ENGLISH": "English (How to keep a mummy)",
```suggestion
          "ENGLISH": "Inglese (How to keep a mummy)",
```

2020-10-01 18:47 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "ENGLISH_STYLISED": "Stylised English",
```suggestion
         "ENGLISH_STYLISED": "Inglese Stilizzato",
```

2020-10-01 18:47 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "NATIVE": "Native (ミイラの飼い方)",
```suggestion
          "NATIVE": "Nativa (ミイラの飼い方)",
```

2020-10-01 18:48 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "NATIVE_STYLISED": "Stylised Native",
```suggestion
          "NATIVE_STYLISED": "Nativa Stilizzata",
```

2020-10-01 18:48 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "ROMAJI_STYLISED": "Stylised Romaji"
```suggestion
          "ROMAJI_STYLISED": "Romaji Stilizzato"
```

2020-10-01 18:48 UTC, Knocks83 commented on src/assets/locales/it.json
> +        "cancelled": "CANCELLED",
```suggestion
        "cancelled": "ANNULLATO",
```

2020-10-01 18:48 UTC, Knocks83 commented on src/assets/locales/it.json
> +        "finished": "FINISHED",
```suggestion
        "finished": "FINITO",
```

2020-10-01 18:48 UTC, Knocks83 commented on src/assets/locales/it.json
> +        "not_yet_released": "NOT YET RELEASED",
```suggestion
        "not_yet_released": "NON ANCORA RILASCIATO",
```

2020-10-01 18:49 UTC, Knocks83 commented on src/assets/locales/it.json
> +        "releasing": "RELEASING"
```suggestion
        "releasing": "IN USCITA"
```

2020-10-01 18:49 UTC, Knocks83 commented on src/assets/locales/it.json
> +      "automatic": "Automatic",
```suggestion
      "automatic": "Automatico",
```

2020-10-01 18:49 UTC, Knocks83 commented on src/assets/locales/it.json
> +      "black": "Black",
```suggestion
      "black": "Nero",
```

2020-10-01 18:49 UTC, Knocks83 commented on src/assets/locales/it.json
> +      "white": "White"
```suggestion
      "white": "Bianco"
```

2020-10-01 18:49 UTC, Knocks83 commented on src/assets/locales/it.json
> +      "all": "All",
```suggestion
      "all": "Tutti",
```

2020-10-01 18:50 UTC, Knocks83 commented on src/assets/locales/it.json
> +      "disabled": "Disabled"
```suggestion
      "disabled": "Disattivato"
```

2020-10-01 18:50 UTC, Knocks83 commented on src/assets/locales/it.json
> +        "episodes": "By Episodes",
```suggestion
        "episodes": "Per Episodio",
```

2020-10-01 18:50 UTC, Knocks83 commented on src/assets/locales/it.json
> +        "score": "By Score",
```suggestion
        "score": "Per Punteggio",
```

2020-10-01 18:50 UTC, Knocks83 commented on src/assets/locales/it.json
> +        "title": "By Title"
```suggestion
        "title": "Per Titolo"
```

2020-10-01 18:50 UTC, Knocks83 commented on src/assets/locales/it.json
> +        "asc": "Ascending",
```suggestion
        "asc": "Ascendente",
```

2020-10-01 18:50 UTC, Knocks83 commented on src/assets/locales/it.json
> +        "desc": "Descending"
```suggestion
        "desc": "Discendente"
```

2020-10-01 18:51 UTC, Knocks83 commented on src/assets/locales/it.json
> +      "timeUntilNextRefresh": "Aggiornamento in: {0}"
```suggestion
      "timeUntilNextRefresh": "Refresh tra: {0}"
```

2020-10-01 18:51 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "headline": "List animation activity",
```suggestion
          "headline": "Limite oggetti per le animazioni",
```

2020-10-01 18:51 UTC, Knocks83 commented on src/assets/locales/it.json
> +          "subtitle": "The selected amount functions as a limit. If more items are shown at the same time, all animations are deactivated to preserve performance."
```suggestion
           "subtitle": "Il valore scelto agisce come limite: se l'utente visualizza più di quel numero di oggetti allo stesso tempo tutte le animazioni vengono disattivate per preservare le prestazioni."
```

2020-10-01 23:03 UTC, Sam-Oak requested changes

2020-10-01 23:03 UTC, Sam-Oak commented on src/assets/locales/pt_BR.json
> +        "desc": "Descending"
```suggestion
        "desc": "Descendente"
```

2020-10-02 09:41 UTC, NicoAiko commented on src/assets/locales/pt_BR.json
> +        "navigationBackgroundBrightness": "Navigation Background Brightness",
```suggestion
        "navigationBackgroundBrightness": "Brilho de fundo da Navegação",
```

2020-10-02 09:45 UTC, NicoAiko commented on src/assets/locales/pt_BR.json
>        "full": "DD [de] MMMM [de] YYYY",
This doesn't need translation as this is a special date format.

2020-10-02 12:57 UTC, CeStain submitted a review, later dismissed

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +        "navigationBackgroundBrightness": "Navigation Background Brightness",
```suggestion
        "navigationBackgroundBrightness": "إضاءة خلفية قائمة التنقل",
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +        "navigationActiveItemColour": "Active Navigation item colour",
```suggestion
        "navigationActiveItemColour": "لون العنصر النشيط في قائمة التنقل",
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +        "navigationBackgroundBlurriness": "Navigation Background Blurriness",
```suggestion
        "navigationBackgroundBlurriness": "ضبابية خلفية قائمة التنقل",
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +        "initialListItemAmount": "Initial amount of shown list items",
```suggestion
        "initialListItemAmount": "عدد العناصر الظاهرة إبتدائباً في القائمة",
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +          "POINT_100": "100 Points (55 / 100)",
```suggestion
          "POINT_100": "100 نقطة (55 / 100)",
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +          "POINT_5": "5 Points (3 / 5)",
```suggestion
          "POINT_10_DECIMAL": "10 نقاط عشرية (5.5 / 10)",
          "POINT_10": "10 نقاط (5 / 10)",
          "POINT_5": "5 نقط (3 / 5)",
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +          "POINT_3": "3 Point Smileys"
```suggestion
          "POINT_3": "3 نقاط ابتسامية"
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +          "ENGLISH": "English (How to keep a mummy)",
```suggestion
          "ENGLISH": "الانجليزية (How to keep a mummy)",
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +          "NATIVE": "Native (ミイラの飼い方)",
```suggestion
          "NATIVE": "اليابانية (ミイラの飼い方)",
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +          "ROMAJI": "Romaji (Miira no Kaikata)",
```suggestion
          "ROMAJI": "رومانجي (Miira no Kaikata)",
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +        "cancelled": "CANCELLED",
```suggestion
        "cancelled": "تم إلغائه",
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +        "finished": "FINISHED",
```suggestion
        "finished": "مُنتهي",
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +        "not_yet_released": "NOT YET RELEASED",
```suggestion
        "not_yet_released": "لم يُصدر بعد",
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +        "releasing": "RELEASING"
```suggestion
        "releasing": "يُصدر حالياً"
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +          "headline": "List animation activity",
```suggestion
          "headline": "حركية القائمة",
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +          "subtitle": "The selected amount functions as a limit. If more items are shown at the same time, all animations are deactivated to preserve performance."
```suggestion
          "subtitle": "العدد المُختار هو الحد. اذا ظهر عدد اكبر في نفس الوقت يتم إلغاء تفعيل كل الحركيات لحفظ الأداء."
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +      "all": "All",
```suggestion
      "all": "الكل",
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +      "disabled": "Disabled"
```suggestion
      "disabled": "الغير مفعل"
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +        "episodes": "By Episodes",
```suggestion
        "episodes": "حسب الحلقات",
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +        "score": "By Score",
```suggestion
        "score": "حسب التقييم",
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +        "title": "By Title"
```suggestion
        "title": "حسب الاسم"
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +        "asc": "Ascending",
```suggestion
        "asc": "تصاعدي",
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
> +        "desc": "Descending"
```suggestion
        "desc": "تنازلي"
```

2020-10-02 12:57 UTC, CeStain commented on src/assets/locales/ar.json
>          "remove": "منزوع",
```suggestion
        "remove": "نزع",
```

2020-10-02 15:17 UTC, Mornwind requested changes
Some string are missing in this PR. I need to create a new one to complete the translation.

2020-10-02 15:17 UTC, Mornwind commented on src/assets/locales/zh_CN.json
> +          "ENGLISH_STYLISED": "Stylised English",
```suggestion
          "ENGLISH_STYLISED": "风格化英文名",
```

2020-10-02 15:17 UTC, Mornwind commented on src/assets/locales/zh_CN.json
> +          "NATIVE_STYLISED": "Stylised Native",
```suggestion
          "NATIVE_STYLISED": "风格化原名",
```

2020-10-02 15:17 UTC, Mornwind commented on src/assets/locales/zh_CN.json
> +          "ROMAJI_STYLISED": "Stylised Romaji"
```suggestion
          "ROMAJI_STYLISED": "风格化罗马字名"
```

2020-10-02 16:50 UTC, Mornwind requested changes
Update Chinese translation.

2020-10-02 16:50 UTC, Mornwind commented on src/assets/locales/zh_CN.json
> +        "initialListItemAmount": "列表项目显示数量初始值",
```suggestion
        "initialListItemAmount": "列表项目初始显示数量",
```

2020-10-02 16:50 UTC, Mornwind commented on src/assets/locales/zh_CN.json
> +          "userTitleLanguageHint": "此项设置用于控制片名以何种语言显示。"
```suggestion
          "userTitleLanguageHint": "此项设置用于修改作品片名在显示时所使用的语言。"
```

2020-10-02 16:50 UTC, Mornwind commented on src/assets/locales/zh_CN.json
> +          "userTitleLanguage": "片名显示语言",
```suggestion
          "userTitleLanguage": "片名语言",
```

2020-10-02 16:50 UTC, Mornwind commented on src/assets/locales/zh_CN.json
> +          "ROMAJI_STYLISED": "风格化罗马字名"
```suggestion
          "ENGLISH": "英文片名（How to keep a mummy）",
          "ENGLISH_STYLISED": "风格化英文片名",
          "NATIVE": "原片名（ミイラの飼い方）",
          "NATIVE_STYLISED": "风格化原片名",
          "ROMAJI": "罗马字片名 (Miira no Kaikata)",
          "ROMAJI_STYLISED": "风格化罗马字片名"
```

2020-10-02 16:50 UTC, Mornwind commented on src/assets/locales/zh_CN.json
> +      "disabled": "已禁用"
```suggestion
      "disabled": "禁用"
```

2020-10-02 16:50 UTC, Sam-Oak requested changes

2020-10-02 16:50 UTC, Sam-Oak commented on src/assets/locales/pt_BR.json
>        "dropped": "Dropado",
```suggestion
      "dropped": "Abandonado",
```

2020-10-02 16:50 UTC, Sam-Oak commented on src/assets/locales/pt_BR.json
> +          "subtitle": "The selected amount functions as a limit. If more items are shown at the same time, all animations are deactivated to preserve performance."
```suggestion
        "navigationBackgroundBlurriness": "Desfoque de Fundo da Navegação",
        "initialListItemAmount": "Quantidade inicial de itens da lista mostrados",
        "listAnimationActivity": {
          "headline": "Atividade de animação da lista",
          "subtitle": "A quantidade selecionada funciona como um limite. Se mais itens forem mostrados ao mesmo tempo, todas as animações serão desativadas para preservar o desempenho."
```

2020-10-02 23:38 UTC, DevonOrxi reviewed
Spanish translation finished for 0.8.0

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +          "scoringFormatHint": "This setting defines how you can score your list entries.",
```suggestion
          "scoringFormatHint": "Esta preferencia define cómo podrás puntuar las entradas de tus listas.",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +          "showExplicitContent": "Show explicit content (18+ Content)",
```suggestion
          "showExplicitContent": "Mostrar contenido explícito",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +          "showExplicitContentHint": "This setting defines if 18+ content will be shown.",
```suggestion
          "showExplicitContentHint": "Esta preferencia define si se mostrará contenido para adultos.",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +          "subHeadline": "Changing these settings may take some time until they come into effect!",
```suggestion
          "subHeadline": "Los cambios en esta preferencia podrían tardar un tiempo hasta entrar en efecto.",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +          "userTitleLanguage": "Title Language",
```suggestion
          "userTitleLanguage": "Lenguaje de los títulos",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +          "userTitleLanguageHint": "This setting defines which title is used for displaying the media's name."
```suggestion
          "userTitleLanguageHint": "Esta preferencia define qué lenguaje se usará para mostrar los nombres de los títulos."
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +        "initialListItemAmount": "Initial amount of shown list items",
```suggestion
        "initialListItemAmount": "Cantidad inicial de ítems a mostrar",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +        "navigationBackgroundBlurriness": "Navigation Background Blurriness",
```suggestion
        "navigationBackgroundBlurriness": "Borrosidad del fondo en la navegación",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +        "navigationBackgroundBrightness": "Navigation Background Brightness",
```suggestion
        "navigationBackgroundBrightness": "Brillo del fondo en la navegación",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +        "navigationActiveItemColour": "Active Navigation item colour",
```suggestion
        "navigationActiveItemColour": "Color del ítem activo en la navegación",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +          "headline": "List animation activity",
```suggestion
          "headline": "Listar actividad de las animaciones",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +          "subtitle": "The selected amount functions as a limit. If more items are shown at the same time, all animations are deactivated to preserve performance."
```suggestion
          "subtitle": "La función seleccionada funciona como límite. Si más ítems se muestran al mismo tiempo, todas las animaciones se desactivarán para mejorar el desempeño del sitio."
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +        "translators": "Translators"
```suggestion
        "translators": "Traductores"
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +          "POINT_10": "10 Points (5 / 10)",
```suggestion
          "POINT_10": "10 Puntos (5 / 10)",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +          "POINT_100": "100 Points (55 / 100)",
```suggestion
          "POINT_100": "100 Puntos (55 / 100)",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +          "POINT_10_DECIMAL": "10 Points Decimal (5.5 / 10)",
```suggestion
          "POINT_10_DECIMAL": "10 Puntos con decimales (5.5 / 10)",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +          "POINT_3": "3 Point Smileys",
```suggestion
          "POINT_3": "3 Puntos con smileys",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +          "POINT_5": "5 Points (3 / 5)"
```suggestion
          "POINT_5": "5 Puntos (3 / 5)"
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +          "ENGLISH": "English (How to keep a mummy)",
```suggestion
          "ENGLISH": "Inglés (How to keep a mummy)",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +          "ENGLISH_STYLISED": "Stylised English",
```suggestion
          "ENGLISH_STYLISED": "Inglés estilizado",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +          "NATIVE": "Native (ミイラの飼い方)",
```suggestion
          "NATIVE": "Nativo (ミイラの飼い方)",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +          "NATIVE_STYLISED": "Stylised Native",
```suggestion
          "NATIVE_STYLISED": "Nativo estilizado",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +          "ROMAJI_STYLISED": "Stylised Romaji"
```suggestion
          "ROMAJI_STYLISED": "Romaji estilizado"
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +        "cancelled": "CANCELLED",
```suggestion
        "cancelled": "CANCELADO",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +        "finished": "FINISHED",
```suggestion
        "finished": "FINALIZADO",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +        "not_yet_released": "NOT YET RELEASED",
```suggestion
        "not_yet_released": "TODAVÍA NO PUBLICADO",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +        "releasing": "RELEASING"
```suggestion
        "releasing": "EN PUBLICACIÓN"
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +      "automatic": "Automatic",
```suggestion
      "automatic": "Automático",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +      "black": "Black",
```suggestion
      "black": "Negro",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +      "white": "White"
```suggestion
      "white": "Blanco"
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +      "disabled": "Disabled"
```suggestion
      "disabled": "Deshabilitado"
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +      "all": "All",
```suggestion
      "all": "Todos",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +        "episodes": "By Episodes",
```suggestion
        "episodes": "Por episodios",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +        "score": "By Score",
```suggestion
        "score": "Por puntuación",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +        "title": "By Title"
```suggestion
        "title": "Por título"
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +        "asc": "Ascending",
```suggestion
        "asc": "Ascendente",
```

2020-10-02 23:38 UTC, DevonOrxi commented on src/assets/locales/es_MX.json
> +        "desc": "Descending"
```suggestion
        "desc": "Descendente"
```

2020-10-03 09:26 UTC, merged