Missing Translations and Notification Bug fix
NicoAiko/mikazuki pull request #217
Opened 2020-12-12 12:05 UTC by NicoAiko

Fixes #216
Adds missing strings to translation files
Fixes bug where notification message text is faulty

2020-12-12 12:06 UTC, NicoAiko commented on src/assets/locales/ar.json
> +    "putOnRepeatList": "Put on repeat list",
@Arabic translation team: Please add a **suggestion** here

2020-12-12 12:06 UTC, NicoAiko commented on src/assets/locales/ar.json
> +    "revertToAiringList": "Revert to airing list"
@Arabic translation team: Please add a **suggestion** here

2020-12-12 12:06 UTC, NicoAiko commented on src/assets/locales/ar.json
> +        "notLoggedIn": "You're currently not logged in! Please do so by clicking on the \"Login\" button below."
@Arabic translation team: Please add a **suggestion** here

2020-12-12 12:07 UTC, NicoAiko commented on src/assets/locales/es_MX.json
> +    "putOnRepeatList": "Put on repeat list",
@Spanish translation team: Please add a **suggestion** here

2020-12-12 12:07 UTC, NicoAiko commented on src/assets/locales/es_MX.json
> +    "revertToAiringList": "Revert to airing list"
@Spanish translation team: Please add a **suggestion** here

2020-12-12 12:07 UTC, NicoAiko commented on src/assets/locales/es_MX.json
> +          "title": "Cambiar puntuación"
@Spanish translation team: Please add a **suggestion** here

2020-12-12 12:07 UTC, NicoAiko commented on src/assets/locales/es_MX.json
> +        "notLoggedIn": "You're currently not logged in! Please do so by clicking on the \"Login\" button below."
@Spanish translation team: Please add a **suggestion** here

2020-12-12 12:08 UTC, NicoAiko commented on src/assets/locales/fr.json
> +    "putOnRepeatList": "Put on repeat list",
@French translation team: Please add a **suggestion** here

2020-12-12 12:09 UTC, NicoAiko commented on src/assets/locales/fr.json
> +    "revertToAiringList": "Revert to airing list"
French translation team: Please add a **suggestion** here

2020-12-12 12:09 UTC, NicoAiko commented on src/assets/locales/fr.json
> +        "notLoggedIn": "You're currently not logged in! Please do so by clicking on the \"Login\" button below."
French translation team: Please add a **suggestion** here

2020-12-12 12:11 UTC, NicoAiko commented on src/assets/locales/id.json
> +    "putOnRepeatList": "Put on repeat list",
Indonesian translation team: Please add a **suggestion** here

2020-12-12 12:11 UTC, NicoAiko commented on src/assets/locales/id.json
> +    "revertToAiringList": "Revert to airing list"
Indonesian translation team: Please add a **suggestion** here

2020-12-12 12:11 UTC, NicoAiko commented on src/assets/locales/id.json
> +        "notLoggedIn": "You're currently not logged in! Please do so by clicking on the \"Login\" button below."
Indonesian translation team: Please add a **suggestion** here

2020-12-12 12:11 UTC, NicoAiko commented on src/assets/locales/it.json
> +    "putOnRepeatList": "Put on repeat list",
Italian translation team: Please add a **suggestion** here

2020-12-12 12:11 UTC, NicoAiko commented on src/assets/locales/it.json
> +    "revertToAiringList": "Revert to airing list"
Italian translation team: Please add a **suggestion** here

2020-12-12 12:11 UTC, NicoAiko commented on src/assets/locales/it.json
> +        "notLoggedIn": "You're currently not logged in! Please do so by clicking on the \"Login\" button below."
Italian translation team: Please add a **suggestion** here

2020-12-12 12:11 UTC, NicoAiko commented on src/assets/locales/my.json
> +    "putOnRepeatList": "Put on repeat list",
Malay translation team: Please add a **suggestion** here

2020-12-12 12:11 UTC, NicoAiko commented on src/assets/locales/my.json
> +    "revertToAiringList": "Revert to airing list"
Malay translation team: Please add a **suggestion** here

2020-12-12 12:11 UTC, NicoAiko commented on src/assets/locales/my.json
> +        "notLoggedIn": "You're currently not logged in! Please do so by clicking on the \"Login\" button below."
Malay translation team: Please add a **suggestion** here

2020-12-12 12:11 UTC, NicoAiko commented on src/assets/locales/pt_BR.json
> +    "putOnRepeatList": "Put on repeat list",
Portuguese translation team: Please add a **suggestion** here

2020-12-12 12:11 UTC, NicoAiko commented on src/assets/locales/pt_BR.json
> +    "revertToAiringList": "Revert to airing list"
Portuguese translation team: Please add a **suggestion** here

2020-12-12 12:11 UTC, NicoAiko commented on src/assets/locales/pt_BR.json
> +        "notLoggedIn": "You're currently not logged in! Please do so by clicking on the \"Login\" button below."
Portuguese translation team: Please add a **suggestion** here

2020-12-12 12:11 UTC, NicoAiko commented on src/assets/locales/tr.json
> +    "putOnRepeatList": "Put on repeat list",
Turkish translation team: Please add a **suggestion** here

2020-12-12 12:11 UTC, NicoAiko commented on src/assets/locales/tr.json
> +    "revertToAiringList": "Revert to airing list"
Turkish translation team: Please add a **suggestion** here

2020-12-12 12:11 UTC, NicoAiko commented on src/assets/locales/tr.json
> +        "notLoggedIn": "You're currently not logged in! Please do so by clicking on the \"Login\" button below."
Turkish translation team: Please add a **suggestion** here

2020-12-12 12:11 UTC, NicoAiko commented on src/assets/locales/zh_CN.json
> +    "putOnRepeatList": "Put on repeat list",
Chinese translation team: Please add a **suggestion** here

2020-12-12 12:11 UTC, NicoAiko commented on src/assets/locales/zh_CN.json
> +    "revertToAiringList": "Revert to airing list"
Chinese translation team: Please add a **suggestion** here

2020-12-12 12:11 UTC, NicoAiko commented on src/assets/locales/zh_CN.json
> +        "notLoggedIn": "You're currently not logged in! Please do so by clicking on the \"Login\" button below."
Chinese translation team: Please add a **suggestion** here

2020-12-12 12:20 UTC, xLn2 commented on src/assets/locales/tr.json
> +    "putOnRepeatList": "Put on repeat list",
```suggestion
    "putOnRepeatList": "Tekrarlananlar listesine ekle",
```

2020-12-12 12:24 UTC, xLn2 commented on src/assets/locales/tr.json
> +        "notLoggedIn": "You're currently not logged in! Please do so by clicking on the \"Login\" button below."
```suggestion
        "notLoggedIn": "Henüz giriş yapmadınız! Lütfen aşağıdaki \"Giriş\" tuşuna basarak giriş işleminizi tamamlayın."
```

2020-12-12 12:30 UTC, xLn2 commented on src/assets/locales/tr.json
> +    "revertToAiringList": "Revert to airing list"
```suggestion
    "revertToAiringList": "İzleniyor listesine geri al"
```

2020-12-12 12:31 UTC, xLn2 commented on src/assets/locales/tr.json
> +        "notLoggedIn": "You're currently not logged in! Please do so by clicking on the \"Login\" button below."
```suggestion
        "notLoggedIn": "Henüz giriş yapmadınız! Lütfen aşağıdaki \"Giriş\" tuşuna basarak işleminizi tamamlayın."
```

2020-12-12 12:32 UTC, xLn2 commented on src/assets/locales/tr.json
> +    "putOnRepeatList": "Put on repeat list",
```suggestion
    "putOnRepeatList": "Tekrarlananlar listesine ekle",
```

2020-12-12 12:43 UTC, TheRaphael0000 commented on src/assets/locales/fr.json
> +    "revertToAiringList": "Revert to airing list"
"toPageTop": "Retourner en haut",
    "putOnRepeatList": "Mettre dans la liste à revoir",
    "revertToAiringList": "Retourner à la liste en cours de diffusion"

2020-12-12 12:43 UTC, TheRaphael0000 commented on src/assets/locales/fr.json
> +        "notLoggedIn": "You're currently not logged in! Please do so by clicking on the \"Login\" button below."
"notLoggedIn": "Vous n'êtes actuellement pas connecté ! Veuillez-vous connectez en cliquant sur le bouton \"Connexion\" ci-dessous."

2020-12-12 12:44 UTC, TheRaphael0000 commented on src/assets/locales/fr.json
> +        "notLoggedIn": "You're currently not logged in! Please do so by clicking on the \"Login\" button below."
```suggestion
        "notLoggedIn": "Vous n'êtes actuellement pas connecté ! Veuillez-vous connectez en cliquant sur le bouton \"Connexion\" ci-dessous."
```

2020-12-12 12:45 UTC, TheRaphael0000 commented on src/assets/locales/fr.json
> +    "revertToAiringList": "Revert to airing list"
```suggestion
    "toPageTop": "Retourner en haut",
    "putOnRepeatList": "Mettre dans la liste à revoir",
    "revertToAiringList": "Retourner à la liste en cours de diffusion"
```

2020-12-12 13:32 UTC, NicoAiko commented on src/assets/locales/fr.json
> +    "revertToAiringList": "Revert to airing list"
I'm not sure if we can input the lines all at once, but we'll try.

2020-12-12 13:34 UTC, NicoAiko commented on src/assets/locales/fr.json
> +    "revertToAiringList": "Revert to airing list"
Thought so.
Now entries are doubled.
Please enter them one by one the next time.

2020-12-12 15:03 UTC, Sam-Oak requested changes

2020-12-12 15:03 UTC, Sam-Oak commented on src/assets/locales/pt_BR.json
> +    "revertToAiringList": "Revert to airing list"
```suggestion
    "revertToAiringList": "Reverter para lista de exibição"
```

2020-12-12 15:03 UTC, Sam-Oak commented on src/assets/locales/pt_BR.json
> +        "notLoggedIn": "You're currently not logged in! Please do so by clicking on the \"Login\" button below."
```suggestion
        "notLoggedIn": "Você não está logado no momento! Por favor faça isso clicando no botão \"Login\" abaixo."
```

2020-12-12 18:15 UTC, CeStain approved these changes

2020-12-12 18:15 UTC, CeStain commented on src/assets/locales/ar.json
> +    "putOnRepeatList": "Put on repeat list",
```suggestion
    "putOnRepeatList": "وضع في قائمة التكرار",
```

2020-12-12 18:15 UTC, CeStain commented on src/assets/locales/ar.json
> +    "revertToAiringList": "Revert to airing list"
```suggestion
    "revertToAiringList": "العوده لقائمة البث"
```

2020-12-12 18:15 UTC, CeStain commented on src/assets/locales/ar.json
> +        "notLoggedIn": "You're currently not logged in! Please do so by clicking on the \"Login\" button below."
```suggestion
        "notLoggedIn": "انت حالياً غير مسجل! يرجى تسجيل الدخول عن طريق الضغط علي زر التسجيل في الأسفل."
```

2020-12-12 18:21 UTC, CeStain submitted a review, later dismissed

2020-12-13 16:17 UTC, nattadasu requested changes
*Localizes Indonesian and Malay lines*

2020-12-13 16:17 UTC, nattadasu commented on src/assets/locales/id.json
> +    "revertToAiringList": "Revert to airing list"
```suggestion
    "putOnRepeatList": "Masukkan ke daftar ulang",
    "revertToAiringList": "Kembalikan ke daftar mengudara"
```

2020-12-13 16:17 UTC, nattadasu commented on src/assets/locales/id.json
> +        "notLoggedIn": "You're currently not logged in! Please do so by clicking on the \"Login\" button below."
```suggestion
        "notLoggedIn": "Kamu belum masuk! Untuk masuk, silakan tekan tombol \"Masuk\" di bawah ini."
```

2020-12-13 16:17 UTC, nattadasu commented on src/assets/locales/my.json
> +    "revertToAiringList": "Revert to airing list"
```suggestion
    "putOnRepeatList": "Masukkan ke senarai ulangan",
    "revertToAiringList": "Kembalikan ke senarai siaran"
```

2020-12-13 16:17 UTC, nattadasu commented on src/assets/locales/my.json
> +        "notLoggedIn": "You're currently not logged in! Please do so by clicking on the \"Login\" button below."
```suggestion
        "notLoggedIn": "Anda belum log masuk! Sila lakukan dengan mengklik pada butang \"Masuk\" di bawah."
```

2020-12-13 16:21 UTC, nattadasu commented on src/assets/locales/my.json
> +    "revertToAiringList": "Revert to airing list"
Hold on, lemme fix that real quick 
![](https://cdn.discordapp.com/emojis/482808973561430018.png?v=1)

2020-12-14 08:12 UTC, Knocks83 requested changes
Fixed IT translation

2020-12-14 08:12 UTC, Knocks83 commented on src/assets/locales/it.json
> +        "notLoggedIn": "You're currently not logged in! Please do so by clicking on the \"Login\" button below."
```suggestion
        "notLoggedIn": "Non sei loggato! Accedi usando il bottone \"Accedi\"."
```

2020-12-14 08:12 UTC, Knocks83 commented on src/assets/locales/it.json
> +    "revertToAiringList": "Revert to airing list"
```suggestion
    "revertToAiringList": "Reinseriscilo nella lista degli anime che stai guardando"
```

2020-12-14 08:12 UTC, Knocks83 commented on src/assets/locales/it.json
> +    "putOnRepeatList": "Put on repeat list",
```suggestion
    "putOnRepeatList": "Inseriscilo nella lista degli anime che stai riguardando",
```

2020-12-16 08:33 UTC, NicoAiko commented on src/assets/locales/ja.json
> +    "revertToAiringList": "「見る」リストに戻す"
```suggestion
    "revertToAiringList": "「視聴中」リストに戻す"
```

2020-12-16 08:33 UTC, NicoAiko commented on src/assets/locales/ja.json
> +    "putOnRepeatList": "リピートリストに移動する",
```suggestion
    "putOnRepeatList": "再視聴中リストに移動する",
```

2020-12-16 08:34 UTC, merged